version: "2"

services:
    webapp:
        build: .
        container_name: adverts.local
        ports:
            - ${WEBAPP_PORT}:8000
        command: cron && tail -f /var/log/cron.log
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - postgres
            - redis
        volumes:
            - .:/webapp

    postgres:
        image: postgres:9.6
        container_name: postgres.local
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    redis:
        image: redis:3.2
        container_name: redis.local
        volumes:
            - redis-volume:/data

volumes:
    postgres-volume:
    redis-volume:
