# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AdvertVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=100)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='base.Advert')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='advertvisit',
            unique_together=set([('advert', 'user_hash')]),
        ),
    ]
